config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  # devise_for :users
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # resources :users, only: :show
  get 'user/:id', to: 'users#show', as: 'user'
  resources :rooms, only: [:index, :create, :show] do
    resources :messages, only: [:create], module: :rooms
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  has_many :participants, dependent: :destroy

  validates :name, presence: true, uniqueness: { case_sensitive: false }

  # broadcast in rooms channel
  after_create_commit { broadcast_append_to :rooms, target: 'js-rooms' }

  scope :public_rooms, -> { where(is_private: false) }

  def participant?(room, user)
    room.participants.where(user_id: user.id).exists?
  end
end

app/controllers/rooms/messages_controller.rb
class Rooms::MessagesController < ApplicationController
  def create
    message = current_user.messages.new(message_params)
    message.room_id = params[:room_id]
    message.save
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_current_room, only: :show
  before_action :set_user_status

  def index
    @room  = Room.new
    @rooms = Room.public_rooms
    @users = User.all_except(current_user)
  end

  def show
    @room  = Room.new
    @rooms = Room.public_rooms

    @message  = Message.new
    all_messages = @current_room.messages.includes(user: [avatar_attachment: [blob: :variant_records]]).order(id: :desc)
    @pagy, @messages = pagy(all_messages, items: 10)
    @messages = @messages.reverse

    @users = User.all_except(current_user)

    render :index
  end

  def create
    @room = Room.create(name: params.dig(:room, :name))
  end

  private

  def load_current_room
    @current_room = Room.find(params[:id])
  end

  def set_user_status
    # when user visit a room page, it's online
    current_user.update!(status: User.statuses[:online]) if current_user
  end
end

app/views/rooms/_form.html.erb
<%= form_with(model: @room, remote: true, class: 'd-flex',
  data: { controller: 'reset-form', action: 'turbo:submit-end->reset-form#reset' }) do |f| %>

  <div class="input-group">
    <%= f.text_field :name, class: 'form-control', autocomplete: :off %>
    <%= f.submit data: { disable_with: false }, class: 'btn btn-primary input-group-append' %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div>
  <%= link_to room.name, room_path(room), class: 'no-underline' %>
</div>

app/views/rooms/index.html+turbo_frame.erb
<%= turbo_frame_tag :page_handler do %>
  <%=
    turbo_stream_action_tag(
      "prepend",
      target: "js-messages-container",
      template: %(#{ render @messages })
    )
  %>

  <%=
    turbo_stream_action_tag(
      "replace",
      target: "pager",
      template: %(#{ render "messages/pager", pagy: @pagy })
    )
  %>
<% end %>

app/views/rooms/index.html.erb
<%= turbo_frame_tag :appearance_channel %>
<div id="js-appearance-channel"></div>

<div id="chatroom-container" class="row bg-secondary text-light">
  <div id="side-panel" class="col-md-4 col-sm-4">
    <div class="d-flex align-items-center justify-content-between current-user-logged-in">
      <div class="icon-container mt-2">
        <%= link_to image_tag(current_user.chat_avatar, class: "chat-pfp") %>
        <%= turbo_stream_from :user_status %>

        <div><%= render "users/status", user: current_user %></div>
      </div>
      <div class="no-underline ms-2 me-auto username text-dark"><%= current_user.email %></div>
    </div>

    <h4 class="text-dark">Users</h4>
    <% # create & subcribe users channel %>
    <%= turbo_stream_from(:users) %>
    <div id="js-users">
      <%= render @users %>
    </div>

    <h4 class="text-dark mt-4">New Room</h4>
    <%= render 'form' %>

    <% # create & subcribe rooms channel %>
    <%= turbo_stream_from(:rooms) %>
    <div id="js-rooms">
      <%= render @rooms %>
    </div>
  </div>

  <div id="room-container" class="col-md-8 col-sm-8 bg-secondary text-light">
    <% if @current_room %>
      <div id="single-room">
        <h4 class="text-center"><%= @user&.email || @current_room.name %></h4>

        <% # create & subcribe room channel %>
        <%= turbo_stream_from(@current_room) %>
        <div id="js-messages" class="messages" data-controller="scroll">
          <%= turbo_frame_tag :page_handler %>
          <%= render "messages/pager", pagy: @pagy %>
          <div id="js-messages-container">
            <%= render @messages %>
          </div>
        </div>

        <%= render 'messages/form' %>
      </div>
    <% end %>
  </div>
</div>